# Generated by Django 2.0.6 on 2018-06-23 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lojista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojista',
            name='CNPJLojista',
            field=models.CharField(help_text='ex. 00.000.000/0000-00', max_length=18, null=True, unique=True, verbose_name='CNPJ do Lojista*'),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='IELojista',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='Inscrição Estadual*'),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='fantasiaLojista',
            field=models.CharField(help_text='Nome Fantasia', max_length=70, verbose_name='Nome Fantasia*'),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='ramoAtividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojista.RamoAtividade', verbose_name='Ramo de Atividade*'),
        ),
        migrations.AlterField(
            model_name='lojista',
            name='razaoLojista',
            field=models.CharField(blank=True, help_text='Razão Social', max_length=70, null=True, verbose_name='Razão Social*'),
        ),
    ]
