# Generated by Django 2.0.6 on 2018-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojista', '0002_auto_20180622_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojista',
            name='IELojista',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Inscrição Estadual*'),
        ),
    ]
