# Generated by Django 2.0.6 on 2018-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
