# Generated by Django 2.0.6 on 2018-06-23 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0002_cupom_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_cupom_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
