# Generated by Django 2.0.6 on 2018-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0003_auto_20180622_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='numeroCupom',
        ),
        migrations.AlterField(
            model_name='cupom',
            name='dataImpressao',
            field=models.DateTimeField(null=True),
        ),
    ]
