# Generated by Django 2.0.6 on 2018-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0004_auto_20180624_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='token',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
