# Generated by Django 2.0.6 on 2018-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0005_cupom_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='token',
            field=models.BinaryField(max_length=200, null=True),
        ),
    ]
