# Generated by Django 2.0.6 on 2018-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dataAtual',
            field=models.DateField(blank=True, null=True, verbose_name='Data Atual'),
        ),
    ]
