# Generated by Django 2.0.6 on 2018-06-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_remove_profile_dataatual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CPF',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
