# Generated by Django 2.0.6 on 2018-06-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0004_auto_20180621_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='RG',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
