# Generated by Django 2.0.6 on 2018-06-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0005_auto_20180622_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CEP',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
