# Generated by Django 2.0.6 on 2018-06-24 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0007_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='valorDocumento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(40, message='O valor do documento deve ser maior que 40 reais!')], verbose_name='Valor do Documento'),
        ),
    ]
