# Generated by Django 2.0.6 on 2018-06-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0008_auto_20180623_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpf',
        ),
    ]
