# Generated by Django 2.0.6 on 2018-06-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0009_delete_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='observacao',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='pendente',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
