# Generated by Django 2.0.6 on 2018-06-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0011_auto_20180624_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='key',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
