# Generated by Django 2.0.6 on 2018-07-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0016_auto_20180628_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='numeroDocumento',
            field=models.CharField(max_length=50, verbose_name='Número do Documento'),
        ),
    ]
