# Generated by Django 2.0.6 on 2018-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0017_auto_20180702_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='numeroDocumento',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número do Documento'),
        ),
    ]
