# Generated by Django 2.0.6 on 2018-07-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0018_auto_20180702_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='photo',
            field=models.FileField(blank=True, upload_to='docs/%Y/%m/%d', verbose_name='Foto do documento fiscal'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='photo2',
            field=models.FileField(blank=True, upload_to='docs2/%Y/%m/%d', verbose_name='Foto do comprovante do cartão'),
        ),
    ]
